version: "2"
services:
    plex:
        image: plexinc/pms-docker
        volumes:
            - ./config/plex:/config
            - ./media/transcode:/transcode
            - ./media/content:/data
            - ./logs/plex:/config/Library/Application Support/Plex Media Server/Logs
        ports:
            - '32400:32400/tcp'
            - '3005:3005/tcp'
            - '8324:8324/tcp'
            - '32469:32469/tcp'
            - '1900:1900/udp'
            - '32410:32410/udp'
            - '32412:32412/udp'
            - '32413:32413/udp'
            - '32414:32414/udp'
        environment:
            - TZ=America/Los_Angeles
            - PGID=1001 
            - PUID=1001

    sabnzbd:
        image: linuxserver/sabnzbd
        volumes:
            - ./config/sabnzbd:/config
            - ./media/downloads:/downloads
            - ./logs/sabnzdb:/config/logs
        ports:
            - '8080:8080'
            - '9090:9090'
        environment:
            - TZ=America/Los_Angeles
            - PGID=1001 
            - PUID=1001

    couchpotato:
        image: linuxserver/couchpotato
        volumes:
            - ./media/content/Movies:/movies
            - ./media/downloads:/downloads
            - ./config/couchpotato:/config
            - ./logs/couchpotato:/config/data/logs
        ports:
            - '5050:5050'
        links:
            - sabnzbd
        environment:
              - TZ=America/Los_Angeles
              - PGID=1001 
              - PUID=1001

    sonarr:
        image: linuxserver/sonarr
        volumes:
            - ./media/content/TV:/tv
            - ./media/downloads:/downloads
            - ./logs/sonarr:/config/logs
            - ./config/sonarr:/config
            - /dev/rtc:/dev/rtc:ro
        links:
            - sabnzbd
        ports:
            - '8989:8989'
        environment:
              - TZ=America/Los_Angeles
              - PGID=1001 
              - PUID=1001
